### ISSUE TITLE
Items returned multiple times.

### ISSUE THREAD

**Issue by mxbossard** [gatling/jsonpath#18]
Hi,

I found a bad behaviour with recursive filtering. Here some tests to identify the problem. I spent some times to figured it out, but cannot correct it.

```scala
  it should "return only one result with object nested in object 1" in {
    JsonPath.query("""$..state.[?(@.text == "(20)")].text""", parseJson(searches)) should findOrderedElements(text("(20)"))
  }

  it should "return only one result with object nested in object 2" in {
    JsonPath.query("""$..[?(@.text == "(20)")].text""", parseJson(searches)) should findOrderedElements(text("(20)"))
  }

  it should "return only one result with object nested in object 3" in {
    JsonPath.query("""$..state..[?(@.text == "(20)")].text""", parseJson(searches)) should findOrderedElements(text("(20)"))
  }
```

In test 2 and 3 a Vector of size 2 is returned.

**Comment by slandelle** [comment]
Hi Maxime,

Could you provide a JSON sample too, please?

**Comment by mxbossard** [comment]
The sample "searches" of JsonPathSpec is sufficient.

**Comment by slandelle** [comment]
@mxbossard test 1 is wrong: there's no `state` node with a `text` child, that's the `1011` child.

**Comment by slandelle** [comment]
The fix for #10 was wrong (kudos to @nremond for find out the culprit commit): on contrary to filters on arrays that have to be applied on children objects, filters on objects apply on the object itself, not its children.

**Comment by nremond** [comment]
That is the opposite of what I said though. I quite disagree with that
choice.

On Sun, Feb 7, 2016 at 11:05 PM, Stephane Landelle <notifications@github.com

**Comment by slandelle** [comment]
`@` means "current element", from Goessner's spec, what makes you think filtering on a object should target its descendants and not the object itself?

**Comment by slandelle** [comment]
Also note that this change gives us the same results than Jayway's implementation, so I'm not the only one to think this way :)

**Comment by nremond** [comment]
Well, the implementation of Goessner does the same as what I say.

Any expression between  square brackets `[]` applies to the children.

Moreover, why do you apply the filter on the children of an array, but for
the map you don't?

On Sun, Feb 7, 2016 at 11:17 PM, Stephane Landelle <notifications@github.com

**Comment by slandelle** [comment]
> Any expression between square brackets `[]` applies to the children.

I think that's something very confusing from Goessner's spec:

| XPath | JSONPath | Description
| -------- | -------------- | ---------------
| /         | . or []          | child operator
| -------- | -------------- | ---------------
| []        | []                | subscript operator. XPath uses it to iterate over element collections and for predicates. In Javascript and JSON it is the native array operator.

So `[]` can mean different things. From my reading:

* when it's a subscript:
  * when it the current node is a collection, iterate
  * otherwise, apply predicate on current node
* otherwise, it means "child operator"
